#!/bin/sh
### BEGIN INIT INFO
# Provides: lampControl
# Required-Start: $local_fs $remote_fs
# Required-Stop: $local_fs $remote_fs
# Should-Start: $network
# Should-Stop: $network
# Default-Start: 2 3 4 5
# Default-Stop: 0 1 6
# Short-Description: Multi-user daemonized version of lampControl.
# Description: Starts the lampControl daemon for all registered users.
### END INIT INFO

NAME="lampControl"
PIDFILE='/var/run/lampControl/lampControl.pid'
DAEMON='/usr/bin/python /opt/YeelightDuskToDawn/lampControl.py'
CONFIG='$PIDFILE'
DAEMON_UID='yeelight'
DAEMON_GID='nasuser'

case "$1" in
    start)
        echo "Starting $NAME"
        mkdir /var/run/lampControl 2> /dev/null
        chown $DAEMON_UID:$DAEMON_UID /var/run/lampControl
        start-stop-daemon --pidfile $PIDFILE --start --background -c $DAEMON_UID -x $DAEMON --chuid $DAEMON_UID:$DAEMON_GID -- $PIDFILE
        ;;
    stop)
        echo "Stopping $NAME"
        start-stop-daemon --pidfile $PIDFILE --stop -x $DAEMON
        rm -r /var/run/lampControl 2> /dev/null
        ;;
    status)
        dbpid=`cat $PIDFILE`
        if [ -z "$dbpid" ]; then
          echo "lampControl not running."
        else
          echo "lampControl running (pid $dbpid)"
          echo `$DAEMON status`
        fi
        ;;
    *)
        echo "Usage: /etc/init.d/lampControl {start|stop|status}"
        exit 1
    esac
exit 0

